- name: Read groups from file
  set_fact:
    groups_list: "{{ lookup('file', group_file).splitlines() }}"

- name: Ensure groups exist (Only GID between 1001 and 1099)
  ansible.builtin.group:
    name: "{{ item.split(':')[0] }}"
    gid: "{{ item.split(':')[2] | int }}"
    state: present
  loop: "{{ groups_list }}"
  when: item.split(':')[2] | int >= 1001 and item.split(':')[2] | int <= 1099
  loop_control:
    label: "Group: {{ item.split(':')[0] }}"
