- name: Generate password file with created users
  lineinfile:
    path: /data/www/password.txt
    line: "{{ item.split(':')[0] }}:{{ lookup('password', '/dev/null length=8 chars=ascii_letters+digits') }}"
    create: yes
  loop: "{{ users_list }}"
  when: item.split(':')[2] | int >= 1001 and item.split(':')[2] | int <= 1099
  loop_control:
    label: "User: {{ item.split(':')[0] }}"

- name: Read password file
  slurp:
    src: "{{ password_file_path }}"
  register: password_file_content

- name: Set passwords for users
  become: true
  user:
    name: "{{ item.split(':')[0] }}"
    password: "{{ item.split(':')[1] | password_hash('sha512') }}"
  loop: "{{ password_file_content.content | b64decode | split('\n') }}"
  when: 
    - password_file_content.content is defined
    - item.split(':') | length == 2
    - item.split(':')[1] is not none
    - item.split(':')[1] != ""
  tags:
    - set_passwords